language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t acehao94/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true acehao94/docker-react npm run test